# Generated by Django 2.2.6 on 2019-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(default=0, max_length=100, verbose_name='开始时间')),
                ('stop_time', models.CharField(default=0, max_length=100, verbose_name='结束时间')),
                ('query_body', models.CharField(default='null', max_length=100, verbose_name='查询内容')),
                ('query_score', models.CharField(default='0.0', max_length=10, verbose_name='查询得分')),
                ('return_body', models.CharField(default='null', max_length=100, verbose_name='返回内容')),
                ('check_tag', models.CharField(default='0', max_length=10, verbose_name='复检标志')),
            ],
            options={
                'db_table': 'query_table',
            },
        ),
    ]
