"""
Django settings for nlp3_cbv project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gwd3umv#b(bpkm6_9yyclwn_66-l+w(2w+t$3qujvcc^3jsuas'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许的主机
ALLOWED_HOSTS = ['*']

# 下面的配置是解决跨域的问题
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS= True
CORS_ALLOW_HEADERS = ('*')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # rest_framework框架
    'nlp_web',  # 注册自然语言处理app
    'blog_comment',  # 注册博客系统app
    "location_transform",  # 注册地理转换app
    'my_media',  # 注册多媒体播放app
    'api',  # 注册用于练习Django rest framework 各个组件的app
    "student_sys.apps.StudentSysConfig",  # 租车学生练习项目、注册qpp的另一种方式、推荐使用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nlp3_cbv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nlp3_cbv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# 数据库相关配置 MySQL数据库的配置方法
# DATABASES = {
#     'default': {
#         # 链接数据库类型
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST': '127.0.0.1',
#         'PORT': 3306,
#         'NAME': 'test',
#         'USER': 'root',
#         'PASSWORD': '123456',
#
#         # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 语言

TIME_ZONE = 'Asia/Shanghai'  # 时区

USE_I18N = True  # 语言

USE_L10N = True  # 数据和时间格式

USE_TZ = True  # 启用时区

# from api.utills.authenticate import TestAuthentication1
# 配置rest framework 的全局配置、项目中所有的app都苏姚通过认证、和权限
# REST_FRAMEWORK = {
#     'UNAUTHENTICATED_USER': None,  # 未认证用户默认值
#     'UNAUTHENTICATED_TOKEN': None,  # 未认证用户token值
#     # 认证
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "api.utills.authenticate.TestAuthentication1",
#     ],
#     # 权限（未实现）
#     "DEFAULT_PERMISSION_CLASSES": [
#         "api.utils.permission.TestPermission",
#     ],
# }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'  # 静态文件别名

# 设置静态文件路径(CSS, JavaScript, Images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    ]  # 列表、可以配置多个静态文件路径


